[package]
name = "newton_rootfinder"
version = "0.1.0"
authors = ["nathan.eckert <nathan.eckert@polytechnique.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
float-cmp = "0.6"

[dependencies]
nalgebra = "0.21.0"
