[package]
name = "newton_rootfinder"
version = "0.2.2"
authors = ["nathan.eckert <nathan.eckert@polytechnique.edu>"]
edition = "2018"
description = "Newton based methods for root finding"
repository = "https://github.com/Nateckert/newton_rootfinder"
keywords = ["Newton", "Raphson", "Root", "Rootfinder"]
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
float-cmp = "0.6"

[dependencies]
nalgebra = "0.21.0"
