name: newton_rootfinder CI build

on:
  push:
    branches: [ development, main ]
  pull_request:
    branches: [ development, main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check formatting
      run: cargo fmt -- --check
  build-nrf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build
    - name: Build additional_log_info
      run: cargo build --features additional_log_info
    - name: Build xml_config_file
      run: cargo build --features xml_config_file
  test-nrf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: cargo test; cargo test --all-features;
  doc-nrf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: doc
        run: cargo doc --no-deps; cargo doc --no-deps --all-features;
  